format = """\
[â•­â•´](fg:arrow)\
$username\
$directory\
$time\
(\
    $git_branch\
    $git_status\
)\
(\
    $python\
    $rust\
    $nodejs\
)\
$cmd_duration
[â•°â”€](fg:arrow)$character\
"""
# Add the modules you need
 
# Disables the blank line at the start of the prompt
add_newline = true
 
palette = "adwaita-dark"
 
 
[palettes.adwaita-dark]
arrow = "#ED9827"
os = "#FFFFFF"
os_admin = "#FFFFFF"
directory = "#c061cb"
time = "#FFDC72"
git = "#f5c211"
git_status = "#ff7800"
clang = "#67E3FF"
rust = "#ffffff"
java = "#FF52A3"
python = "#B4F9F8"
node = "#81FF85"
conda = "#BAF5C0"
duration = "#91FFE7"
text_color = "#26272A"
text_light = "#26272A"
custom_quiz = "#ffffff"
 
[username]
style_user = 'os'
style_root = 'os_admin'
format = 'ğŸ‘»'
#format = '[î‚¶]($style)[ó±«±  ](bg:$style fg:text_color)[î‚´]($style)'
disabled = false
show_always = true
 
[character]
success_symbol = "[ó°Ÿ](fg:arrow)"
error_symbol = "[ó°Ÿ](fg:red)"
 
[directory]
format = " [î‚¶](fg:directory)[ï¼  $path ]($style)[$read_only]($read_only_style)[î‚´](fg:directory)"
truncation_length = 2
style = "fg:text_color bg:directory"
read_only_style = "fg:text_color bg:directory"
before_repo_root_style = "fg:text_color bg:directory"
truncation_symbol = "â€¦/"
truncate_to_repo = true
read_only =" î©µ "
 
[custom.quiz]
detect_extensions = ['.qz']
detect_files = ['01.qz']
format = '[î‚¶]($style)["ğŸ€ ONIICHNAX Quiz "](bg:$style fg:text_color)[î‚´]($style)'
style = "fg:text_color bg:time"
 
 
[time]
disabled = true
format = " [î‚¶](fg:time)[ï€— $time]($style)[î‚´](fg:time)"
time_format = "%H:%M"
style = "fg:text_color bg:time"
 
[cmd_duration]
format = " [î‚¶](fg:duration)[ï‰” $duration]($style)[î‚´](fg:duration)"
style = "fg:text_light bg:duration"
min_time = 500
disabled = true
 
[git_branch]
format = " [î‚¶](fg:git)[$symbol$branch](fg:text_light bg:git)[î‚´](fg:git)"
symbol = "ï˜ "
 
[git_status]
format = '([ î‚¶](fg:git_status)[ $all_status$ahead_behind ]($style)[î‚´](fg:git_status))'
style = "fg:text_light bg:git_status"
disabled = false
 
[docker_context]
disabled=true
symbol = "ïŒˆ "
 
[package]
disabled=true
 
 
[nodejs]
format = "[ î‚¶](fg:node)[$symbol$version]($style)[î‚´](fg:node)"
style = "bg:node fg:text_light"
symbol = "îœ˜ "
version_format = "${raw}"
disabled=false
 
[rust]
format ='[ î‚¶](fg:rust)[$symbol$version](bg:rust fg:text_color)[î‚´](fg:rust)'
symbol = "ğŸ¦€ "
version_format = "${raw}"
style = "fg:text_light bg:python"
disabled=false
 
[python]
disabled=true
format = '[ î‚¶](fg:python)[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)[î‚´](fg:python)'
symbol = "î˜† "
version_format = "${raw}"
style = "fg:text_light bg:python"
 
[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Gentoo = "ïŒ "
Linux = "ïŒš "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
openSUSE = "ïŒ” "
Pop = "îŠ£ "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ï”— "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ï…º "
#ONIICHANX = "ó±«±  "
ONIICHANX = "ğŸ‘» "
